version: "2.3"


services:
  ccvg:

    build:
      context: ./ccvgd-backend
    ports:
      - "80"
    depends_on:
      - db
    restart: always
    links:
      - db
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.python-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.routers.ccvg.middlewares=python-redirect-websecure"
      - "traefik.http.routers.ccvg.entrypoints=web"
      - "traefik.http.routers.ccvg.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.python-ssl.entrypoints=websecure"
      - "traefik.http.routers.python-ssl.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.python-ssl.tls=true"


  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro


  angular:
      build:
        context: ./ccvgd-frontend
        args:  
          - PRODUCTION=${PRODUCTION_FLAG}
      ports:
        - "80"
      depends_on:
        - ccvg
        - db
      environment:
        - ./.env
        - API_URL=${API_URL}
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.angular-redirect-websecure.redirectscheme.scheme=https"
        - "traefik.http.routers.angular.middlewares=angular-redirect-websecure"
        - "traefik.http.routers.angular.entrypoints=web"
        - "traefik.http.routers.angular.rule=Host(`${CCVGD_DOMAIN}`)"
        - "traefik.http.routers.angular-ssl.entrypoints=websecure"
        - "traefik.http.routers.angular-ssl.rule=Host(`${CCVGD_DOMAIN}`)"
        - "traefik.http.routers.angular-ssl.tls=true"



  traefik:
    image: traefik:v2.7
    command:
      - --providers.docker
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker.exposedByDefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.file.filename=/etc/conf/tls.yaml
      - "--log=true"
      - "--log.level=DEBUG"
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TLS_YAML_PATH:-./traefik/tls.yaml}:/etc/conf/tls.yaml
      - ./certs:/etc/ssl/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    depends_on:
      - db
      - ccvg
      - angular
    restart: always


