global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true

#  only for dev

  insecure: true

entryPoints:
  web:
    address: :80
#    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          scheme: https

  websecure:
    address: :443


providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

  file:
    directory: /etc/traefik
    watch: false
