from Category import CATEGORIES
import process

read_csv_dirct = "All Datasets and Data Dictionary"
output_csv_dirct = "Database Data"

print("---------------")
process.create_csv_gazetteerInformation(read_csv_dirct, output_csv_dirct, input_file="1__gazetteer_information.csv")
print("end")
print("---------------")
process.create_csv_city_county_province(read_csv_dirct, output_csv_dirct, read_file_name="2__village_information.csv")
print("end")
print("---------------")
process.create_csv_village_and_address(read_csv_dirct, output_csv_dirct, read_file_name="2__village_information.csv")
print("end")
print("---------------")
process.create_csv_category(CATEGORIES, output_csv_dirct)
print("end")
print("---------------")
process.create_csv_economy_economyUnit(read_csv_dirct, output_csv_dirct, yearly_file="10__economy___yearly.csv", range_file="10__economy___range.csv")
print("end")
print("---------------")
process.create_csv_education_educationUnit(read_csv_dirct, output_csv_dirct, yearly_file="12__education___yearly.csv", range_file="12__education___range.csv")
print("end")
print("---------------")
process.create_csv_ethnic_ethnicUnit(read_csv_dirct,output_csv_dirct, yearly_file="7__ethnic_groups___yearly.csv", range_file="7__ethnic_groups___range.csv")
print("end")
print("---------------")
process.create_csv_naturalDisasters(read_csv_dirct, output_csv_dirct, file="4__natural_disasters.csv")
print("end")
print("---------------")
process.create_csv_lastName_lastNameCategory(read_csv_dirct, output_csv_dirct, file="5__last_names.csv")
print("end")
print("---------------")
process.create_csv_population_populationUnit(read_csv_dirct, output_csv_dirct, yearly_file="8__population_and_migration___yearly.csv", range_file="8__population_and_migration___range.csv")
print("end")
print("---------------")
process.create_csv_military_militaryUnit(read_csv_dirct, output_csv_dirct, yearly_file="9____military_politics_and_management___yearly.csv", range_file="9____military_politics_and_management___range.csv")
print("end")
print("---------------")
process.create_csv_familyplanning_familyplanningUnit(read_csv_dirct, output_csv_dirct, yearly_file="11__family_planning___yearly.csv", range_file="11__family_planning___range.csv")
print("end")
print("---------------")
process.create_csv_natrualenvironment_Unit(read_csv_dirct, output_csv_dirct, input_file = "3__natural_environment.csv")
print("end")
print("---------------")
process.create_csv_villagegeography_Unit(read_csv_dirct, output_csv_dirct, input_file = "2__village_information.csv")
print("end")
print("---------------")
process.create_csv_year_of_first_availability_purchase(read_csv_dirct, output_csv_dirct, input_file = "6__year_of_first_availability_purchase.csv")
print("end")