class Table:
    TABLES = {}

    TABLES['gazetteerInformation'] = ("CREATE TABLE `gazetteerInformation_村志信息` ("
                                      "  `gazetteerId_村志代码` int(11) NOT NULL,"
                                      "  `gazetteerTitle_村志书名` varchar(100) NOT NULL,"
                                      "  `gazetteerTitleHanyuPinyin_村志书名汉语拼音` varchar(100) NOT NULL,"
                                      "  `yearOfPublication_出版年` varchar(4) NOT NULL,"
                                      "  `publicationType_出版类型` varchar(100) DEFAULT NULL,"
                                      "  PRIMARY KEY (`gazetteerId_村志代码`)"
                                      ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['village'] = ("CREATE TABLE `village_村` ("
                         "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                         "  `gazetteerId_村志代码` int(11) NOT NULL,"
                         "  `villageId_村庄代码` varchar(100) DEFAULT NULL,"
                         "  `nameChineseCharacters_村名汉字` varchar(100) DEFAULT NULL,"
                         "  `nameHanyuPinyin_村名汉语拼音` varchar(100) DEFAULT NULL,"
                         "  PRIMARY KEY (`villageInnerId_村庄内部代码`,`gazetteerId_村志代码`),"
                         "  KEY `gazetteerId_index` (`gazetteerId_村志代码`),"
                         "  KEY `villageInnerId_index` (`villageInnerId_村庄内部代码`),"
                         "  CONSTRAINT `village_村_ibfk_1` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`)"
                         ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['city'] = ("CREATE TABLE `city_市` ("
                      "  `cityId_市代码` int(11) NOT NULL,"
                      "  `nameChineseCharacters_市汉字` varchar(100) DEFAULT NULL,"
                      "  `nameHanyuPinyin_市汉语拼音` varchar(100) DEFAULT NULL,"
                      "  PRIMARY KEY (`cityId_市代码`)"
                      " ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['county'] = ("CREATE TABLE `county_县` ("
                        " `countyDistrictId_县或区代码` int(11) NOT NULL,"
                        " `nameChineseCharacters_县或区汉字` varchar(100) DEFAULT NULL,"
                        " `nameHanyuPinyin_县或区汉语拼音` varchar(100) DEFAULT NULL,"
                        " PRIMARY KEY (`countyDistrictId_县或区代码`)"
                        ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['province'] = ("CREATE TABLE `province_省` ("
                          "  `provinceId_省代码` int(11) NOT NULL,"
                          "  `nameChineseCharacters_省汉字` varchar(100) DEFAULT NULL,"
                          "  `nameHanyuPinyin_省汉语拼音` varchar(100) DEFAULT NULL,"
                          "  PRIMARY KEY (`provinceId_省代码`)"
                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['villageCountyCityProvince'] = ("CREATE TABLE `villageCountyCityProvince_村县市省` ("
                                           "  `gazetteerId_村志代码` int(11) NOT NULL,"
                                           "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                                           "  `countyDistrictId_县或区代码` int(11) DEFAULT NULL,"
                                           "  `cityId_市代码` int(11) DEFAULT NULL,"
                                           "  `provinceId_省代码` int(11) DEFAULT NULL,"
                                           "  PRIMARY KEY (`gazetteerId_村志代码`,`villageInnerId_村庄内部代码`),"
                                           "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                                           "  KEY `cityId_市代码` (`cityId_市代码`),"
                                           "  KEY `provinceId_省代码` (`provinceId_省代码`),"
                                           "  KEY `villagecountycityprovince_村县市省_ibfk_2` (`countyDistrictId_县或区代码`),"
                                           "  CONSTRAINT `villagecountycityprovince_村县市省_ibfk_1` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `village_村` (`gazetteerId_村志代码`),"
                                           "  CONSTRAINT `villagecountycityprovince_村县市省_ibfk_2` FOREIGN KEY (`countyDistrictId_县或区代码`) REFERENCES `county_县` (`countydistrictid_县或区代码`),"
                                           "  CONSTRAINT `villagecountycityprovince_村县市省_ibfk_3` FOREIGN KEY (`cityId_市代码`) REFERENCES `city_市` (`cityid_市代码`),"
                                           "  CONSTRAINT `villagecountycityprovince_村县市省_ibfk_4` FOREIGN KEY (`provinceId_省代码`) REFERENCES `province_省` (`provinceid_省代码`)"
                                           ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['naturalEnvironmentCategory'] = ("CREATE TABLE `naturalEnvironmentCategory_自然环境类` ("
                                            "  `categoryId_类别代码` int(11) NOT NULL,"
                                            "  `name_名称` varchar(100) NOT NULL,"
                                            "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                            "  PRIMARY KEY (`categoryId_类别代码`)"
                                            ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['naturalEnvironmentUnit'] = ("CREATE TABLE `naturalEnvironmentUnit_自然环境单位` ("
                                        "  `unitId_单位代码` int(11) NOT NULL,"
                                        "  `name_名称` varchar(100) NOT NULL,"
                                        "  PRIMARY KEY (`unitId_单位代码`)"
                                        ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['naturalEnvironment'] = ("CREATE TABLE `naturalEnvironment_自然环境` ("
                                    "  `gazetteerId_村志代码` int(11) NOT NULL,"
                                    "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                                    "  `categoryId_类别代码` int(11) NOT NULL,"
                                    "  `unitId_单位代码` int(11) NOT NULL,"
                                    "  `data_数据` float DEFAULT NULL,"
                                    "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`unitId_单位代码`,`villageInnerId_村庄内部代码`),"
                                    "  KEY `categoryId_类别代码` (`categoryId_类别代码`),"
                                    "  KEY `unitId_单位代码` (`unitId_单位代码`),"
                                    "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                                    "  KEY `naturalenvironment_自然环境_ibfk_4_idx` (`villageInnerId_村庄内部代码`),"
                                    "  CONSTRAINT `naturalenvironment_自然环境_ibfk_1` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `naturalEnvironmentCategory_自然环境类` (`categoryid_类别代码`),"
                                    "  CONSTRAINT `naturalenvironment_自然环境_ibfk_2` FOREIGN KEY (`unitId_单位代码`) REFERENCES `naturalEnvironmentUnit_自然环境单位` (`unitid_单位代码`),"
                                    "  CONSTRAINT `naturalenvironment_自然环境_ibfk_3` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                                    "  CONSTRAINT `naturalenvironment_自然环境_ibfk_4` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['firstAvailabilityorPurchaseCategory'] = ("CREATE TABLE `firstAvailabilityorPurchaseCategory_第一次购买或拥有年份类` ("
                                                     "  `categoryId_类别代码` int(11) NOT NULL,"
                                                     "  `name_名称` varchar(100) NOT NULL,"
                                                     "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                                     "  PRIMARY KEY (`categoryId_类别代码`)"
                                                     ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['firstAvailabilityorPurchase'] = ("CREATE TABLE `firstAvailabilityorPurchase_第一次购买或拥有年份` ("
                                             "  `gazetteerId_村志代码` int(11) NOT NULL,"
                                             "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                                             "  `categoryId_类别代码` int(11) NOT NULL,"
                                             "  `year_年份` year(4) DEFAULT NULL,"
                                             "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`villageInnerId_村庄内部代码`),"
                                             "  KEY `categoryId_类别代码` (`categoryId_类别代码`),"
                                             "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                                             "  KEY `firstavailabilityorpurchase_第一次购买或拥有年份__idx` (`villageInnerId_村庄内部代码`),"
                                             "  CONSTRAINT `firstavailabilityorpurchase_第一次购买或拥有年份_ibfk_1` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `firstAvailabilityorPurchaseCategory_第一次购买或拥有年份类` (`categoryid_类别代码`),"
                                             "  CONSTRAINT `firstavailabilityorpurchase_第一次购买或拥有年份_ibfk_2` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                                             "  CONSTRAINT `firstavailabilityorpurchase_第一次购买或拥有年份_ibfk_3` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                                             ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['familyPlanningCategory'] = ("CREATE TABLE `familyplanningcategory_计划生育类` ("
                                        "  `categoryId_类别代码` int(11) NOT NULL,"
                                        "  `name_名称` varchar(100) NOT NULL,"
                                        "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                        "  PRIMARY KEY (`categoryId_类别代码`)"
                                        ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['familyPlanningUnit'] = ("CREATE TABLE `familyplanningunit_计划生育单位` ("
                                    "`unitId_单位代码` int(11) NOT NULL,"
                                    "`name_名称` varchar(100) DEFAULT NULL,"
                                    "PRIMARY KEY (`unitId_单位代码`)"
                                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['familyPlanning'] = ("CREATE TABLE `familyplanning_计划生育` ("
                                "  `gazetteerId_村志代码` int(11) NOT NULL,"
                                "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                                "  `categoryId_类别代码` int(11) NOT NULL,"
                                "  `startYear_开始年` year(4) NOT NULL,"
                                "  `endYear_结束年` year(4) NOT NULL,"
                                "  `unitId_单位代码` int(11) NOT NULL,"
                                "  `data_数据` float DEFAULT NULL,"
                                "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`startYear_开始年`,`endYear_结束年`,`unitId_单位代码`,`villageInnerId_村庄内部代码`),"
                                "  KEY `ethnicgroups_计划生育_ibfk_1_idx` (`categoryId_类别代码`),"
                                "  KEY `ethnicgroups_计划生育_ibfk_2_idx` (`unitId_单位代码`),"
                                "  KEY `ethnicgroups_计划生育_ibfk_4_idx` (`villageInnerId_村庄内部代码`),"
                                "  CONSTRAINT `ethnicgroups_计划生育_ibfk_2` FOREIGN KEY (`unitId_单位代码`) REFERENCES `familyplanningunit_计划生育单位` (`unitid_单位代码`),"
                                "  CONSTRAINT `ethnicgroups_计划生育_ibfk_3` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                                "  CONSTRAINT `ethnicgroups_计划生育_ibfk_4` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`),"
                                "  CONSTRAINT `familyplanning_计划生育_ibfk_1` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `familyplanningcategory_计划生育类` (`categoryid_类别代码`)"
                                ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['militaryCategory'] = ("CREATE TABLE `militarycategory_军事类` ("
                                  "  `categoryId_类别代码` int(11) NOT NULL,"
                                  "  `name_名称` varchar(100) NOT NULL,"
                                  "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                  "  PRIMARY KEY (`categoryId_类别代码`)"
                                  ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['militaryUnit'] = ("CREATE TABLE `militaryunit_军事单位` ("
                              "  `unitId_单位代码` int(11) NOT NULL,"
                              "  `name_名称` varchar(100) DEFAULT NULL,"
                              "  PRIMARY KEY (`unitId_单位代码`)"
                              ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['military'] = ("CREATE TABLE `military_军事` ("
                          "  `gazetteerId_村志代码` int(11) NOT NULL,"
                          "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                          "  `categoryId_类别代码` int(11) NOT NULL,"
                          "  `startYear_开始年` year(4) NOT NULL,"
                          "  `endYear_结束年` year(4) NOT NULL,"
                          "  `unitId_单位代码` int(11) NOT NULL,"
                          "  `data_数据` float DEFAULT NULL,"
                          "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`endYear_结束年`,`unitId_单位代码`,`startYear_开始年`,`villageInnerId_村庄内部代码`),"
                          "  KEY `military_军事_ibfk_1_idx` (`categoryId_类别代码`),"
                          "  KEY `military_军事_ibfk_2_idx` (`unitId_单位代码`),"
                          "  KEY `military_军事_ibfk_4_idx` (`villageInnerId_村庄内部代码`),"
                          "  CONSTRAINT `military_军事_ibfk_1` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `militarycategory_军事类` (`categoryid_类别代码`),"
                          "  CONSTRAINT `military_军事_ibfk_2` FOREIGN KEY (`unitId_单位代码`) REFERENCES `militaryunit_军事单位` (`unitid_单位代码`),"
                          "  CONSTRAINT `military_军事_ibfk_3` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                          "  CONSTRAINT `military_军事_ibfk_4` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['educationCategory'] = ("CREATE TABLE `educationCategory_教育类` ("
                                   "  `categoryId_类别代码` int(11) NOT NULL,"
                                   "  `name_名称` varchar(100) NOT NULL,"
                                   "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                   "  PRIMARY KEY (`categoryId_类别代码`)"
                                   ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['educationUnit'] = ("CREATE TABLE `educationUnit_教育单位` ("
                               "  `unitId_单位代码` int(11) NOT NULL,"
                               "  `name_名称` varchar(100) DEFAULT NULL,"
                               "  PRIMARY KEY (`unitId_单位代码`)"
                               ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['education'] = ("CREATE TABLE `education_教育` ("
                           "  `gazetteerId_村志代码` int(11) NOT NULL,"
                           "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                           "  `categoryId_类别代码` int(11) NOT NULL,"
                           "  `startYear_开始年` year(4) NOT NULL,"
                           "  `endYear_结束年` year(4) NOT NULL,"
                           "  `unitId_单位代码` int(11) NOT NULL,"
                           "  `data_数据` float DEFAULT NULL,"
                           "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`startYear_开始年`,`endYear_结束年`,`unitId_单位代码`,`villageInnerId_村庄内部代码`),"
                           "  KEY `categoryId_类别代码` (`categoryId_类别代码`),"
                           "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                           "  KEY `education_教育_ibfk_3_idx` (`unitId_单位代码`),"
                           "  KEY `education_教育_ibfk_4_idx` (`villageInnerId_村庄内部代码`),"
                           "  CONSTRAINT `education_教育_ibfk_1` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `educationCategory_教育类` (`categoryid_类别代码`),"
                           "  CONSTRAINT `education_教育_ibfk_2` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                           "  CONSTRAINT `education_教育_ibfk_3` FOREIGN KEY (`unitId_单位代码`) REFERENCES `educationUnit_教育单位` (`unitid_单位代码`),"
                           "  CONSTRAINT `education_教育_ibfk_4` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                           ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['villageGeographyCategory'] = ("CREATE TABLE `villageGeographyCategory_村庄地理类` ("
                                          "  `categoryId_类别代码` int(11) NOT NULL,"
                                          "  `name_名称` varchar(100) NOT NULL,"
                                          "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                          "  PRIMARY KEY (`categoryId_类别代码`)"
                                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['villageGeographyUnit'] = ("CREATE TABLE `villageGeographyUnit_村庄地理单位` ("
                                      "  `unitId_单位代码` int(11) NOT NULL AUTO_INCREMENT,"
                                      "  `name_名称` varchar(100) NOT NULL,"
                                      "  PRIMARY KEY (`unitId_单位代码`)"
                                      ") ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['villageGeography'] = ("CREATE TABLE `villageGeography_村庄地理` ("
                                  "  `gazetteerId_村志代码` int(11) NOT NULL,"
                                  "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                                  "  `categoryId_类别代码` int(11) NOT NULL,"
                                  "  `unitId_单位代码` int(11) NOT NULL,"
                                  "  `data_数据` varchar(100) DEFAULT NULL,"
                                  "  PRIMARY KEY (`gazetteerId_村志代码`,`villageInnerId_村庄内部代码`,`categoryId_类别代码`,`unitId_单位代码`),"
                                  "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                                  "  KEY `categoryId_类别代码` (`categoryId_类别代码`),"
                                  "  KEY `villagegeography_村庄地理_ibfk_3_idx` (`unitId_单位代码`),"
                                  "  KEY `villagegeography_村庄地理_ibfk_4_idx` (`villageInnerId_村庄内部代码`),"
                                  "  CONSTRAINT `villagegeography_村庄地理_ibfk_1` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                                  "  CONSTRAINT `villagegeography_村庄地理_ibfk_2` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `villageGeographyCategory_村庄地理类` (`categoryid_类别代码`),"
                                  "  CONSTRAINT `villagegeography_村庄地理_ibfk_3` FOREIGN KEY (`unitId_单位代码`) REFERENCES `villageGeographyUnit_村庄地理单位` (`unitid_单位代码`),"
                                  "  CONSTRAINT `villagegeography_村庄地理_ibfk_4` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                                  ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['naturalDisastersCategory'] = ("CREATE TABLE `naturalDisastersCategory_自然灾害类` ("
                                          "  `categoryId_类别代码` int(11) NOT NULL,"
                                          "  `name_名称` varchar(100) NOT NULL,"
                                          "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                          "  PRIMARY KEY (`categoryId_类别代码`)"
                                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['naturalDisasters'] = ("CREATE TABLE `naturalDisasters_自然灾害` ("
                                  "  `gazetteerId_村志代码` int(11) NOT NULL,"
                                  "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                                  "  `categoryId_类别代码` int(11) NOT NULL,"
                                  "  `year_年份` year(4) NOT NULL,"
                                  "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`year_年份`,`villageInnerId_村庄内部代码`),"
                                  "  KEY `categoryId_类别代码` (`categoryId_类别代码`),"
                                  "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                                  "  KEY `naturaldisasters_自然灾害_ibfk_2_idx` (`villageInnerId_村庄内部代码`),"
                                  "  CONSTRAINT `naturaldisasters_自然灾害_ibfk_1` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                                  "  CONSTRAINT `naturaldisasters_自然灾害_ibfk_2` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `naturalDisastersCategory_自然灾害类` (`categoryid_类别代码`),"
                                  "  CONSTRAINT `naturaldisasters_自然灾害_ibfk_3` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                                  ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['populationCategory'] = ("CREATE TABLE `populationcategory_人口类` ("
                                    "  `categoryId_类别代码` int(11) NOT NULL,"
                                    "  `name_名称` varchar(100) NOT NULL,"
                                    "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                    "  PRIMARY KEY (`categoryId_类别代码`)"
                                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['populationUnit'] = ("CREATE TABLE `populationunit_人口单位` ("
                                "  `unitId_单位代码` int(11) NOT NULL,"
                                "  `name_名称` varchar(100) NOT NULL,"
                                "  PRIMARY KEY (`unitId_单位代码`)"
                                ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['population'] = ("CREATE TABLE `population_人口` ("
                            "  `gazetteerId_村志代码` int(11) NOT NULL,"
                            "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                            "  `categoryId_类别代码` int(11) NOT NULL,"
                            "  `startYear_开始年` year(4) NOT NULL,"
                            "  `endYear_结束年` year(4) NOT NULL,"
                            "  `unitId_单位代码` int(11) DEFAULT NULL,"
                            "  `data_数据` float DEFAULT NULL,"
                            "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`startYear_开始年`,`endYear_结束年`,`villageInnerId_村庄内部代码`),"
                            "  KEY `population_人口_ibfk_1_idx` (`categoryId_类别代码`),"
                            "  KEY `population_人口_ibfk_2_idx` (`unitId_单位代码`),"
                            "  KEY `population_人口_ibfk_4_idx` (`villageInnerId_村庄内部代码`),"
                            "  CONSTRAINT `population_人口_ibfk_1` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `populationcategory_人口类` (`categoryid_类别代码`),"
                            "  CONSTRAINT `population_人口_ibfk_2` FOREIGN KEY (`unitId_单位代码`) REFERENCES `populationunit_人口单位` (`unitid_单位代码`),"
                            "  CONSTRAINT `population_人口_ibfk_3` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                            "  CONSTRAINT `population_人口_ibfk_4` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                            ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['ethnicCategory'] = ("CREATE TABLE `ethnicGroupsCategory_民族类` ("
                                "  `categoryId_类别代码` int(11) NOT NULL,"
                                "  `name_名称` varchar(100) DEFAULT NULL,"
                                "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                "  PRIMARY KEY (`categoryId_类别代码`)"
                                ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['ethnicUnit'] = ("CREATE TABLE `ethnicGroupsUnit_民族单位` ("
                            "  `unitId_单位代码` int(11) NOT NULL,"
                            "  `name_名称` varchar(100) NOT NULL,"
                            "  PRIMARY KEY (`unitId_单位代码`)"
                            ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['ethnic'] = ("CREATE TABLE `ethnicGroups_民族` ("
                        "  `gazetteerId_村志代码` int(11) NOT NULL,"
                        "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                        "  `categoryId_类别代码` int(11) NOT NULL,"
                        "  `startYear_开始年` year(4) NOT NULL,"
                        "  `endYear_结束年` year(4) NOT NULL,"
                        "  `unitId_单位代码` int(11) NOT NULL,"
                        "  `data_数据` float DEFAULT NULL,"
                        "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`startYear_开始年`,`endYear_结束年`,`unitId_单位代码`,`villageInnerId_村庄内部代码`),"
                        "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                        "  KEY `unitId_单位代码` (`unitId_单位代码`),"
                        "  KEY `categoryId_类别代码_idx` (`categoryId_类别代码`),"
                        "  KEY `ethnicgroups_民族_ibfk_4_idx` (`villageInnerId_村庄内部代码`),"
                        "  CONSTRAINT `ethnicgroups_民族_ibfk_1` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `ethnicGroupsCategory_民族类` (`categoryid_类别代码`),"
                        "  CONSTRAINT `ethnicgroups_民族_ibfk_2` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                        "  CONSTRAINT `ethnicgroups_民族_ibfk_3` FOREIGN KEY (`unitId_单位代码`) REFERENCES `ethnicGroupsUnit_民族单位` (`unitid_单位代码`),"
                        "  CONSTRAINT `ethnicgroups_民族_ibfk_4` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                        ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['economyCategory'] = ("CREATE TABLE `economyCategory_经济类` ("
                                 "  `categoryId_类别代码` int(11) NOT NULL,"
                                 "  `name_名称` varchar(100) NOT NULL,"
                                 "  `parentId_父类代码` int(11) DEFAULT NULL,"
                                 "  PRIMARY KEY (`categoryId_类别代码`)"
                                 ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['economyUnit'] = ("CREATE TABLE `economyUnit_经济单位` ("
                             "  `unitId_单位代码` int(11) NOT NULL,"
                             "  `name_名称` varchar(100) NOT NULL,"
                             "  PRIMARY KEY (`unitId_单位代码`)"
                             ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['economy'] = ("CREATE TABLE `economy_经济` ("
                         "  `gazetteerId_村志代码` int(11) NOT NULL,"
                         "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                         "  `categoryId_类别代码` int(11) NOT NULL,"
                         "  `startYear_开始年` year(4) NOT NULL,"
                         "  `endYear_结束年` year(4) NOT NULL,"
                         "  `unitId_单位代码` int(11) NOT NULL,"
                         "  `data_数据` float DEFAULT NULL,"
                         "  PRIMARY KEY (`gazetteerId_村志代码`,`categoryId_类别代码`,`startYear_开始年`,`endYear_结束年`,`unitId_单位代码`,`villageInnerId_村庄内部代码`),"
                         "  KEY `unitId_单位代码` (`unitId_单位代码`),"
                         "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                         "  KEY `categoryId_idx` (`categoryId_类别代码`),"
                         "  KEY `villageInnerId_idx` (`villageInnerId_村庄内部代码`),"
                         "  CONSTRAINT `categoryId` FOREIGN KEY (`categoryId_类别代码`) REFERENCES `economyCategory_经济类` (`categoryid_类别代码`),"
                         "  CONSTRAINT `gazetteerId` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                         "  CONSTRAINT `unitId` FOREIGN KEY (`unitId_单位代码`) REFERENCES `economyUnit_经济单位` (`unitid_单位代码`),"
                         "  CONSTRAINT `villageInnerId_economy` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageInnerId_村庄内部代码`)"
                         ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['lastNameCategory'] = ("CREATE TABLE `lastNameCategory_姓氏类别` ("
                                  "  `categoryId_类别代码` int(11) NOT NULL,"
                                  "  `nameChineseCharacters_姓氏汉字` varchar(100) NOT NULL,"
                                  "  `nameHanyuPinyin_姓氏汉语拼音` varchar(100) NOT NULL,"
                                  "  PRIMARY KEY (`categoryId_类别代码`)"
                                  ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")

    TABLES['lastName'] = ("CREATE TABLE `lastName_姓氏` ("
                          "  `gazetteerId_村志代码` int(11) NOT NULL,"
                          "  `villageInnerId_村庄内部代码` varchar(100) NOT NULL,"
                          "  `firstlastNamesId_姓氏代码` int(11) DEFAULT NULL,"
                          "  `secondlastNamesId_姓氏代码` int(11) DEFAULT NULL,"
                          "  `thirdlastNamesId_姓氏代码` int(11) DEFAULT NULL,"
                          "  `fourthlastNamesId_姓氏代码` int(11) DEFAULT NULL,"
                          "  `fifthlastNamesId_姓氏代码` int(11) DEFAULT NULL,"
                          "  `totalNumberofLastNamesinVillage_姓氏总数` int(11) DEFAULT NULL,"
                          "  PRIMARY KEY (`gazetteerId_村志代码`,`villageInnerId_村庄内部代码`),"
                          "  KEY `firstlastNamesId_姓氏代码` (`firstlastNamesId_姓氏代码`),"
                          "  KEY `secondlastNamesId_姓氏代码` (`secondlastNamesId_姓氏代码`),"
                          "  KEY `thirdlastNamesId_姓氏代码` (`thirdlastNamesId_姓氏代码`),"
                          "  KEY `fourthlastNamesId_姓氏代码` (`fourthlastNamesId_姓氏代码`),"
                          "  KEY `fifthlastNamesId_姓氏代码` (`fifthlastNamesId_姓氏代码`),"
                          "  KEY `gazetteerId_村志代码` (`gazetteerId_村志代码`),"
                          "  KEY `lastname_姓氏_ibfk_7_idx` (`villageInnerId_村庄内部代码`),"
                          "  CONSTRAINT `lastname_姓氏_ibfk_1` FOREIGN KEY (`firstlastNamesId_姓氏代码`) REFERENCES `lastNameCategory_姓氏类别` (`categoryid_类别代码`),"
                          "  CONSTRAINT `lastname_姓氏_ibfk_2` FOREIGN KEY (`secondlastNamesId_姓氏代码`) REFERENCES `lastNameCategory_姓氏类别` (`categoryid_类别代码`),"
                          "  CONSTRAINT `lastname_姓氏_ibfk_3` FOREIGN KEY (`thirdlastNamesId_姓氏代码`) REFERENCES `lastNameCategory_姓氏类别` (`categoryid_类别代码`),"
                          "  CONSTRAINT `lastname_姓氏_ibfk_4` FOREIGN KEY (`fourthlastNamesId_姓氏代码`) REFERENCES `lastNameCategory_姓氏类别` (`categoryid_类别代码`),"
                          "  CONSTRAINT `lastname_姓氏_ibfk_5` FOREIGN KEY (`fifthlastNamesId_姓氏代码`) REFERENCES `lastNameCategory_姓氏类别` (`categoryid_类别代码`),"
                          "  CONSTRAINT `lastname_姓氏_ibfk_6` FOREIGN KEY (`gazetteerId_村志代码`) REFERENCES `gazetteerInformation_村志信息` (`gazetteerId_村志代码`),"
                          "  CONSTRAINT `lastname_姓氏_ibfk_7` FOREIGN KEY (`villageInnerId_村庄内部代码`) REFERENCES `village_村` (`villageinnerid_村庄内部代码`)"
                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;")
