version: "2.2"


services:
  ccvg:
    image: ccvgd_backend:latest
    ports:
      - "5050:5050"
    depends_on:
      - db
    restart: always
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: local1
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ccvg_5_18
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  angular:
    image: ccvgd-frontend:latest
    ports:
      - "4200:80"
    restart: always



