[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "WARN"
  format = "common"

[api]
  dashboard = true
  insecure = true

[ping]

[accessLog]

[providers]
  [providers.docker]
#     watch = true
#     exposedByDefault = false
    endpoint = "unix:///var/run/docker.sock"
#     swarmMode = false
#     useBindPortIP = false
#     network = "traefik"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"


# defaultEntryPoints = ["http", "https"]
# [entryPoints]
#   [entryPoints.http]
#     address = ":80"
# #     entryPoint = "https"
# #   [entryPoints.https]
# #     [entryPoints.web.http.redirections]
# #       [entryPoints.web.http.redirections.entryPoint]
# #         to = "websecure"
# #         scheme = "https"
#   [entryPoints.https]
#     address = ":443"
#
# [accesslog]
#
# [api]
# dashboard = true
#
# [providers]
#   [providers.docker]
#     exposedByDefault = false
